#
# application.yml — главный конфигурационный файл Spring Boot.

Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.

server:
  port: 8080
spring:
  application:
    name: BANK-CARD control
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_rest
    password: 1
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    
